{
 "title": "Tenants Dashboard",
 "time": { "from": "2020-12-17T23:04:56.936Z", "to": "2020-12-17T23:36:14.145Z" },
 "panels": [
  {
   "title": "Instances per tenant",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "resource.label.namespace_name" ],
      "metricKind": "GAUGE",
      "metricType": "custom.googleapis.com/nuxeo/dropwizard5_nuxeo.instance-up_counter",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jx-preprod",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Instances per tenant",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "resource.label.namespace_name" ],
      "metricKind": "GAUGE",
      "metricType": "custom.googleapis.com/nuxeo/dropwizard5_nuxeo.instance-up_counter",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jx-preprod",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Completed Works",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.label.cluster_name",
       "=",
       "multitenants"
      ],
      "groupBys": [ "metric.label.namespace_name" ],
      "metricKind": "GAUGE",
      "metricType": "custom.googleapis.com/nuxeo/dropwizard5_nuxeo.works.global.queue.completed_gauge",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jx-preprod",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Async Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [],
      "groupBys": [ "metric.label.namespace_name" ],
      "metricKind": "GAUGE",
      "metricType": "custom.googleapis.com/nuxeo/dropwizard5_nuxeo.async.load_gauge",
      "perSeriesAligner": "ALIGN_INTERPOLATE",
      "projectName": "jx-preprod",
      "unit": "1",
      "valueType": "DOUBLE"
     }
    }
   ]
  }
 ]
}