nameOverride: test01
replicaCount: 1
ingress:
  hostname: company-f.multitenant.nuxeo.com
  tls: 
    - hosts:
      - company-f.multitenant.nuxeo.com
      secretName: static-wildcard-tls
customProperties:
  tenant: |
    nuxeo.tenantId=test01
    # k8s_pod vs k8s_container vs default
    nuxeo.stackdriver.forceResourceType=k8s_pod
    metrics.streams.enabled=true
extraVolumes:
  - name: gcpcconfig
    secret:
      secretName: nuxeo-test01-gcp-sa
